// AUTO-GENERATED by scripts/build-puzzles.cjs — do not edit by hand.
// Each puzzle is a verified "mate in 1": the side to move has at least one move
// that delivers immediate checkmate. `mates` lists EVERY correct answer (uci),
// so the solver accepts any mating move, not just one canonical line.

export interface Puzzle {
  id: string;
  fen: string;
  sideToMove: 'w' | 'b';
  theme: string;
  difficulty: number;
  mates: string[];
}

export const PUZZLES: Puzzle[] = [
  {
    "id": "m1-001",
    "fen": "6k1/5ppp/8/8/4K3/8/8/R7 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "a1a8"
    ]
  },
  {
    "id": "m1-002",
    "fen": "6k1/5ppp/8/8/4K3/8/8/Q7 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "a1a8"
    ]
  },
  {
    "id": "m1-003",
    "fen": "6k1/5ppp/8/8/4K3/8/8/1R6 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "b1b8"
    ]
  },
  {
    "id": "m1-004",
    "fen": "6k1/5ppp/8/8/4K3/8/8/1Q6 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "b1b8"
    ]
  },
  {
    "id": "m1-005",
    "fen": "6k1/5ppp/8/8/4K3/8/8/2R5 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "c1c8"
    ]
  },
  {
    "id": "m1-006",
    "fen": "6k1/5ppp/8/8/4K3/8/8/2Q5 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "c1c8"
    ]
  },
  {
    "id": "m1-007",
    "fen": "6k1/5ppp/8/8/4K3/8/8/3R4 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "d1d8"
    ]
  },
  {
    "id": "m1-008",
    "fen": "6k1/5ppp/8/8/4K3/8/8/3Q4 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "d1d8"
    ]
  },
  {
    "id": "m1-009",
    "fen": "1k6/ppp5/8/8/4K3/8/8/3R4 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "d1d8"
    ]
  },
  {
    "id": "m1-010",
    "fen": "1k6/ppp5/8/8/4K3/8/8/3Q4 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "d1d8"
    ]
  },
  {
    "id": "m1-011",
    "fen": "1k6/ppp5/8/8/4K3/8/8/5R2 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "f1f8"
    ]
  },
  {
    "id": "m1-012",
    "fen": "1k6/ppp5/8/8/4K3/8/8/5Q2 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "f1f8"
    ]
  },
  {
    "id": "m1-013",
    "fen": "1k6/ppp5/8/8/4K3/8/8/6R1 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "g1g8"
    ]
  },
  {
    "id": "m1-014",
    "fen": "1k6/ppp5/8/8/4K3/8/8/6Q1 w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "g1g8"
    ]
  },
  {
    "id": "m1-015",
    "fen": "1k6/ppp5/8/8/4K3/8/8/7R w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "h1h8"
    ]
  },
  {
    "id": "m1-016",
    "fen": "1k6/ppp5/8/8/4K3/8/8/7Q w - - 0 1",
    "sideToMove": "w",
    "theme": "Back-rank mate",
    "difficulty": 1,
    "mates": [
      "h1h8"
    ]
  },
  {
    "id": "m1-017",
    "fen": "7k/5Q2/6K1/8/8/8/8/8 w - - 0 1",
    "sideToMove": "w",
    "theme": "Queen & king mate",
    "difficulty": 2,
    "mates": [
      "f7e8",
      "f7f8",
      "f7g7",
      "f7h7"
    ]
  },
  {
    "id": "m1-018",
    "fen": "k7/2Q5/1K6/8/8/8/8/8 w - - 0 1",
    "sideToMove": "w",
    "theme": "Queen & king mate",
    "difficulty": 2,
    "mates": [
      "c7c8",
      "c7d8",
      "c7b7",
      "c7a7"
    ]
  },
  {
    "id": "m1-019",
    "fen": "7k/R7/1R6/8/8/8/8/6K1 w - - 0 1",
    "sideToMove": "w",
    "theme": "Two-rook mate",
    "difficulty": 2,
    "mates": [
      "b6b8"
    ]
  },
  {
    "id": "m1-020",
    "fen": "7k/6pp/8/8/8/8/1Q6/3R2K1 w - - 0 1",
    "sideToMove": "w",
    "theme": "Heavy-piece mate",
    "difficulty": 2,
    "mates": [
      "b2b8",
      "d1d8"
    ]
  }
];
