// Build + verify the daily-puzzle set.
//
// Every candidate FEN is checked with chess.js: we keep it ONLY if the side to
// move has at least one move that delivers checkmate (a real "mate in 1"). We
// also record every mating move so the solver can accept ANY correct answer and
// never tell a kid their winning move was "wrong". Output is written to
// lib/puzzles.ts. Run: node scripts/build-puzzles.cjs
const fs = require('fs');
const path = require('path');
const { Chess } = require('chess.js');

// ---- Candidate positions (white or black to move; all "mate in 1") ----------
// Templated back-rank mates for visual variety (different files / both wings /
// rook + queen), plus a few classic king-and-queen and two-rook patterns.
const candidates = [];

// Back-rank, black king castled kingside (g8) with f7/g7/h7 pawns. White heavy
// piece climbs an open file to the 8th. Files a–e are clear (f is blocked by f7).
const kingsideRanks = (rank1) => `6k1/5ppp/8/8/4K3/8/8/${rank1} w - - 0 1`;
// Back-rank, black king queenside (b8) with a7/b7/c7 pawns. Files d–h are clear.
const queensideRanks = (rank1) => `1k6/ppp5/8/8/4K3/8/8/${rank1} b - - 0 1`; // placeholder, fixed below

function fileRow(fileIdx, letter) {
  // a row of the board with `letter` on file fileIdx (0=a..7=h), rest empty.
  const before = fileIdx;
  const after = 7 - fileIdx;
  return `${before ? before : ''}${letter}${after ? after : ''}`;
}

// Kingside back-rank: attacker on rank 1, files a..e, rook then queen.
for (const f of [0, 1, 2, 3, 4]) {
  candidates.push({ fen: kingsideRanks(fileRow(f, 'R')), theme: 'Back-rank mate', difficulty: 1 });
  candidates.push({ fen: kingsideRanks(fileRow(f, 'Q')), theme: 'Back-rank mate', difficulty: 1 });
}
// Queenside back-rank: attacker on rank 1, files d..h, white to move.
for (const f of [3, 4, 5, 6, 7]) {
  const fen = `1k6/ppp5/8/8/4K3/8/8/${fileRow(f, 'R')} w - - 0 1`;
  candidates.push({ fen, theme: 'Back-rank mate', difficulty: 1 });
  const fenQ = `1k6/ppp5/8/8/4K3/8/8/${fileRow(f, 'Q')} w - - 0 1`;
  candidates.push({ fen: fenQ, theme: 'Back-rank mate', difficulty: 1 });
}

// King & queen corner mates.
candidates.push({ fen: '7k/5Q2/6K1/8/8/8/8/8 w - - 0 1', theme: 'Queen & king mate', difficulty: 2 });
candidates.push({ fen: 'k7/2Q5/1K6/8/8/8/8/8 w - - 0 1', theme: 'Queen & king mate', difficulty: 2 });
candidates.push({ fen: '8/8/8/8/8/2k5/2Q5/2K5 b - - 0 1', theme: 'Queen & king mate', difficulty: 2 });

// Two-rook ladder mates.
candidates.push({ fen: '7k/R7/1R6/8/8/8/8/6K1 w - - 0 1', theme: 'Two-rook mate', difficulty: 2 });
candidates.push({ fen: 'k7/7R/1R6/8/8/8/8/6K1 w - - 0 1', theme: 'Two-rook mate', difficulty: 2 });
candidates.push({ fen: '7k/6pp/8/8/8/8/1Q6/3R2K1 w - - 0 1', theme: 'Heavy-piece mate', difficulty: 2 });

// ---- Verify: keep only positions with a real mate-in-1 --------------------
const puzzles = [];
const seen = new Set();
for (const c of candidates) {
  let game;
  try {
    game = new Chess(c.fen);
  } catch (e) {
    console.warn('SKIP (illegal fen):', c.fen, e.message);
    continue;
  }
  // Reject positions where the side NOT to move is already in check (illegal).
  const moves = game.moves({ verbose: true });
  const mates = [];
  for (const m of moves) {
    const g2 = new Chess(c.fen);
    g2.move({ from: m.from, to: m.to, promotion: m.promotion });
    if (g2.isCheckmate()) mates.push(m.from + m.to + (m.promotion || ''));
  }
  if (mates.length === 0) {
    console.warn('SKIP (no mate-in-1):', c.fen);
    continue;
  }
  if (seen.has(c.fen)) continue;
  seen.add(c.fen);
  puzzles.push({
    id: 'm1-' + String(puzzles.length + 1).padStart(3, '0'),
    fen: c.fen,
    sideToMove: game.turn(), // 'w' | 'b'
    theme: c.theme,
    difficulty: c.difficulty,
    mates, // every move (uci) that delivers checkmate
  });
}

console.log(`Kept ${puzzles.length} / ${candidates.length} candidates.`);

const header = `// AUTO-GENERATED by scripts/build-puzzles.cjs — do not edit by hand.
// Each puzzle is a verified "mate in 1": the side to move has at least one move
// that delivers immediate checkmate. \`mates\` lists EVERY correct answer (uci),
// so the solver accepts any mating move, not just one canonical line.

export interface Puzzle {
  id: string;
  fen: string;
  sideToMove: 'w' | 'b';
  theme: string;
  difficulty: number;
  mates: string[];
}

export const PUZZLES: Puzzle[] = ${JSON.stringify(puzzles, null, 2)};
`;

const out = path.join(__dirname, '..', 'lib', 'puzzles.ts');
fs.writeFileSync(out, header);
console.log('Wrote', out);
